### PR TITLE
Template for imagery request

### PR DESCRIPTION
**Pull request by pratikyadav**
Added a [github issue template](https://github.com/blog/2111-issue-and-pull-request-templates) for more structured request. 

This includes-
- Description explaining the context of request in terms of area, resolution, date  and other factors.
- Link to HOT wiki activation page 
- Gist of geo Jon for requested area.
- Isuues with current imagery
- Level of urgency
- Requirement of Post-event imagery.

### CODE REVIEW

**Comment by smit1678** [comment]
Dig this @pratikyadav. Really like issue templates and this will be helpful. 

@cgiovando can you merge, I don't have write access.

**Comment by dalekunce** [comment]
👍 @pratikyadav

**Comment by pratikyadav** [comment]
👋  @cgiovando  @harry-wood @mikelmaron 
can you have a look at this PR and let me know if there is any-thing else required here? If not, would be nice to merge it.

Thanks.

**Comment by mikelmaron** [comment]
lgtm @pratikyadav. I don't have write access to merge but happy to if I can get that. @cgiovando?

**Comment by cgiovando** [comment]
Don't think I can - ccing @dodobas

**Comment by mikelmaron** [comment]
@dodobas in addition can you spread write access around to a few of us?

**Comment by pratikyadav** [comment]
_Ping_

@dodobas would be nice if we can get this moving.

**Pull request merged**
