### PR TITLE
Refactoring imagery-search base map selection.

### LINKED ISSUE #88: Improve indication that you can click to change maps
On the imagery search page, look to improve the indication that you can click to change the maps. Right now there is no mouse indication or visual indication of the map selected.

### PR DESCRIPTION
**Pull request by sharkinsspatial**
Refactoring imagery-search to support improved testability, better follow Redux best practices and adhere to Mapbox GL state management [best practices](https://blog.mapbox.com/mapbox-gl-js-in-a-reactive-application-e08eecf0221b) closes #88.

### CODE REVIEW

**Comment by tombh** [comment]
Great! Really nice coding style; clear, well thought out and nice refactoring. You clearly know your React :)

One thing that could have been good would be to have used the same testing approach as oam-browser, ie `mocha` and `sinon` (oh, actually you'd only see `sinon` if you looked at my unmerged branches). It's not a big deal, `tape` and `babel-require-plugin` are great too. But it would just make things easier when merging back into oam-browser. Don't feel like you have to change this though. BTW, similarly I hope that imagery-coordination-api will be merged into oam-catalog.

Anyway, looks great, nice work :)

**Comment by sharkinsspatial** [comment]
Updated .travis.yml to force use of Trusty environment rather than Precision.  CI builds are now passing correctly.  One additional note on updating Mapbox GL JS maps via style diffs.  There is some [code](https://github.com/sharkinsspatial/imagery-coordination/blob/fc6551eccff77818aaee56cb23f7cfb0332a426b/app/assets/scripts/components/imagery-search.js#L75-L89) in this pull request that can be simplified once this upstream Mapbox GL JS [issue](https://github.com/mapbox/mapbox-gl-js/issues/3893) fix is released.

**Comment by smit1678** [comment]
@sharkinsspatial Feel free to assign this to me when this is ready to be reviewed and merged (we can use that method for future PRs as well).

**Comment by smit1678** [comment]
Closing out in preference for a new PR, #141

**Pull request closed without merging**
