### PR TITLE
Feature/map refactor

### PR DESCRIPTION
**Pull request by danielfdsilva**
Needed API functionality: https://github.com/hotosm/imagery-requests-api/pull/18

Main features:
- Show status colored points for requests
- Show status colored polygons for tasks
- Show popup with information on point/polygon click
- Show other tasks (grayed out) on the task page
- Implement new approach for imagery compare

### CODE REVIEW

**Comment by danielfdsilva** [comment]
Color pallet for statuses:
screen_shot_2017-01-20_at_3 30 39_pm

- Open: #5ABDCB
- In Progress: #D0EC77
- Completed: #72C97D
- Closed: #A5B1B5
- Canceled: #EA4F54

**Comment by olafveerman** [comment]
@danielfdsilva Looks good overall. Couple of comments:

- the maps on the [imagery search page](http://localhost:3000/#/imagery-search) are not synced  
`mapbox-gl-sync-move:23 Uncaught (in promise) TypeError: a.on is not a function`
- on the [task page](http://localhost:3000/#/requests/58505aa36a45544cf5bf876f/tasks/58505e916a45544cf5bf8774) of a task that has siblings, the popup of the siblings are not aligned with their polygons. In this case I clicked on the lower-left polygon of Bairro Alto / Cais do Sodré:  
image
- when I zoom in on the map of the [task dashboard](http://localhost:3000/#/dashboard), the points disappear when going from z9 -> z10

**Comment by olafveerman** [comment]
@danielfdsilva Reviewed again. The issue with the map not syncing does not occur on a clean build.

**Comment by danielfdsilva** [comment]
@olafveerman The points disappear and the polygons appear, but they are still too small to be noticed. I adjusted the zoom threshold a bit. Should be good.

**Comment by nbumbarger** [comment]
@danielfdsilva the filter dropdowns on the homepage no longer update the features shown on the map. I have a couple of small suggestions beyond that:
- Add a legend explaining the status colors (or just add to the about section).
- Add a "Full extent" option to the map's "Jump to" dropdown, so the map can easily be reset to show all requests after having zoomed in.
- "Skip this step" on the imagery search strikes me as awkward phrasing. It makes it seem like there should be a way to actually select an image source. What about two buttons: "Make request" to continue if there's no good TMS imagery, or "Cancel" to return to the homepage.

**Comment by danielfdsilva** [comment]
@nbumbarger That's a new desired behavior. The map shows all the available requests in the system and the list shows a subset that can be filtered. Also, the both elements don't look interconnected. The position of the filters leads to think that it's only for the list.

As for the other points:
- Good idea on the legend
- "Full Extend" could be a useful option
- I don't love it either but I didn't have a better alternative. When you click the "add request" button on the homepage you're taken to this page. Having another button that says "Add request" seems strange, but maybe it's me. I don't agree with the "cancel" as this page is not exactly a step but a page that can be viewed independently.

**Comment by danielfdsilva** [comment]
@nbumbarger please open issues for the legend and the full extent options

**Pull request merged**
