### PR TITLE
Feature/misc

### PR DESCRIPTION
**Pull request by nbumbarger**
Implements outstanding issues, including:
- Updates the features and map view when filter conditions are changed (https://github.com/hotosm/imagery-requests/issues/54);
- Shows markers instead of polygons when zoom level is low (https://github.com/hotosm/imagery-requests/issues/55)
- Improves editing by visually disabling the delete button when a feature isn't selected, always allowing vertices to be moved, and always deleting the feature when it is selected and the delete button is pressed.

### CODE REVIEW

**Comment by danielfdsilva** [comment]
@nbumbarger The user dashboard map is still not updating when features change.
Login with the `coordinator`, and switch to the created tab. The map doesn't update.

**Comment by nbumbarger** [comment]
Hmm, I hadn't tested the dashboard tabs, but I'll do that now. The map filtering commit applies to the homepage: changing the author, status, and time interval dropdowns will refresh the map data and view.

**Comment by danielfdsilva** [comment]
@nbumbarger did a new tests and figure out the conditions.
- if the user doesn't have any assigned tasks and you click `created` the map doesn't update. (test with the coordinator)
- I confirm that if there's an assigned task it works as supposed however if you filter the tasks to a point where it yields no results, the map is not cleared. (for example: created tab, in progress status)

**Comment by nbumbarger** [comment]
@danielfdsilva That bug should be fixed.

**Comment by olafveerman** [comment]
Looks good from a functionality perspective. I'll leave it to @danielfdsilva for final review

**Pull request merged**
